LastSessions<|||>1<|||>AI.MySQL
LastActiveSession<|||>1<|||>AI.MySQL
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,10
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,0
MainWinOnMonitor<|||>3<|||>0
ColWidths_MainForm.ListDatabases<|||>1<|||>150,80,50,50,50,50,50,50,50,50,120
ColsVisible_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColPositions_MainForm.ListDatabases<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10
ColSort_MainForm.ListDatabases<|||>1<|||>0,0
ColWidths_MainForm.ListVariables<|||>1<|||>160,200,428
ColsVisible_MainForm.ListVariables<|||>1<|||>0,1,2
ColPositions_MainForm.ListVariables<|||>1<|||>0,1,2
ColSort_MainForm.ListVariables<|||>1<|||>0,0
ColWidths_MainForm.ListStatus<|||>1<|||>160,428,100,100
ColsVisible_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColPositions_MainForm.ListStatus<|||>1<|||>0,1,2,3
ColSort_MainForm.ListStatus<|||>1<|||>0,0
ColWidths_MainForm.ListProcesses<|||>1<|||>70,80,80,80,80,50,50,300
ColsVisible_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColPositions_MainForm.ListProcesses<|||>1<|||>0,1,2,3,4,5,6,7
ColSort_MainForm.ListProcesses<|||>1<|||>0,1
ColWidths_MainForm.ListCommandStats<|||>1<|||>120,100,100,100,368
ColsVisible_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColPositions_MainForm.ListCommandStats<|||>1<|||>0,1,2,3,4
ColSort_MainForm.ListCommandStats<|||>1<|||>1,1
ColWidths_MainForm.ListTables<|||>1<|||>120,70,70,120,120,70,100,50,70,70,70,70,70,90,120,70,70,70,50
ColsVisible_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,18
ColPositions_MainForm.ListTables<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
ColSort_MainForm.ListTables<|||>1<|||>0,0
MainWinWidth<|||>3<|||>993
MainWinHeight<|||>3<|||>525
CreateDbCollation<|||>1<|||>utf8mb4_0900_ai_ci
ColWidths_frmTableEditor.listColumns<|||>1<|||>42,100,152,90,60,65,50,117,130,139,100,100
ColsVisible_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColPositions_frmTableEditor.listColumns<|||>1<|||>0,1,2,3,4,5,6,7,8,9,10,11
ColSort_frmTableEditor.listColumns<|||>1<|||>-1,0
ColWidths_frmTableEditor.treeIndexes<|||>1<|||>919,100,80,120
ColsVisible_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3
ColPositions_frmTableEditor.treeIndexes<|||>1<|||>0,1,2,3
ColSort_frmTableEditor.treeIndexes<|||>1<|||>-1,0
ColWidths_frmTableEditor.listForeignKeys<|||>1<|||>76,80,100,80,80,80
ColsVisible_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColPositions_frmTableEditor.listForeignKeys<|||>1<|||>0,1,2,3,4,5
ColSort_frmTableEditor.listForeignKeys<|||>1<|||>-1,0
ColWidths_frmTableEditor.listCheckConstraints<|||>1<|||>200,296
ColsVisible_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColPositions_frmTableEditor.listCheckConstraints<|||>1<|||>0,1
ColSort_frmTableEditor.listCheckConstraints<|||>1<|||>-1,0
MainWinMaximized<|||>3<|||>1
querymemoheight<|||>3<|||>413
SQLFile0<|||>1<|||>C:\laragon\www\aisu\user_registration\registration_system.sql
FileDialogEncoding_MainForm<|||>3<|||>0
TabCloseOnDoubleClick<|||>3<|||>0
ExportSQL_Filenames<|||>1<|||>C:\laragon\www\aisu\Main_Pages_AISU\registration\user_registration\registration_system.sql<{{{><}}}>
FindDialogSearchHistory<|||>1<|||>AISU: Our vision is to be a globally competitive institution of higher learning.<br>Our mission is to provide quality education, innovative research, and community engagement.<{{{><}}}>
MemoEditorWrap<|||>3<|||>1
Servers\AI.MySQL\SessionCreated<|||>1<|||>2024-07-30 11:53:11
Servers\AI.MySQL\Host<|||>1<|||>127.0.0.1
Servers\AI.MySQL\WindowsAuth<|||>3<|||>0
Servers\AI.MySQL\CleartextPluginEnabled<|||>3<|||>0
Servers\AI.MySQL\User<|||>1<|||>root
Servers\AI.MySQL\Password<|||>1<|||>9
Servers\AI.MySQL\LoginPrompt<|||>3<|||>0
Servers\AI.MySQL\Port<|||>1<|||>3306
Servers\AI.MySQL\NetType<|||>3<|||>0
Servers\AI.MySQL\Compressed<|||>3<|||>0
Servers\AI.MySQL\LocalTimeZone<|||>3<|||>0
Servers\AI.MySQL\QueryTimeout<|||>3<|||>30
Servers\AI.MySQL\KeepAlive<|||>3<|||>20
Servers\AI.MySQL\FullTableStatus<|||>3<|||>1
Servers\AI.MySQL\Databases<|||>1<|||>
Servers\AI.MySQL\Library<|||>1<|||>libmysql.dll
Servers\AI.MySQL\Comment<|||>1<|||>
Servers\AI.MySQL\StartupScriptFilename<|||>1<|||>
Servers\AI.MySQL\TreeBackground<|||>3<|||>536870911
Servers\AI.MySQL\SshExecutable<|||>1<|||>
Servers\AI.MySQL\SSHtunnelHost<|||>1<|||>
Servers\AI.MySQL\SSHtunnelHostPort<|||>3<|||>22
Servers\AI.MySQL\SSHtunnelUser<|||>1<|||>
Servers\AI.MySQL\SSHtunnelPassword<|||>1<|||>3
Servers\AI.MySQL\SSHtunnelTimeout<|||>3<|||>4
Servers\AI.MySQL\SSHtunnelPrivateKey<|||>1<|||>
Servers\AI.MySQL\SSHtunnelPort<|||>3<|||>3307
Servers\AI.MySQL\SSL_Active<|||>3<|||>0
Servers\AI.MySQL\SSL_Key<|||>1<|||>
Servers\AI.MySQL\SSL_Cert<|||>1<|||>
Servers\AI.MySQL\SSL_CA<|||>1<|||>
Servers\AI.MySQL\SSL_Cipher<|||>1<|||>
Servers\AI.MySQL\IgnoreDatabasePattern<|||>1<|||>
Servers\AI.MySQL\LogFileDdl<|||>3<|||>0
Servers\AI.MySQL\LogFileDml<|||>3<|||>0
Servers\AI.MySQL\LogFilePath<|||>1<|||>C:\Users\Admin\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\AI.MySQL\RefusedCount<|||>3<|||>2
Servers\AI.MySQL\ServerVersionFull<|||>1<|||>8.0.30 - MySQL Community Server - GPL
Servers\AI.MySQL\ConnectCount<|||>3<|||>39
Servers\AI.MySQL\ServerVersion<|||>3<|||>80030
Servers\AI.MySQL\LastConnect<|||>1<|||>2025-03-12 21:26:28
Servers\AI.MySQL\lastUsedDB<|||>1<|||>aisu
Servers\AI.MySQL\aisu|chat_logs\Sort<|||>1<|||>0_user_message|
Servers\AI.MySQL\aisu|faculty\Sort<|||>1<|||>0_username|
Servers\AI.MySQL\aisu|history\Sort<|||>1<|||>0_id|
Servers\AI.MySQL\aisu|login\MemoEditorHighlighter_password<|||>1<|||>HTML
Servers\AI.MySQL\aisu|messages\Sort<|||>1<|||>1_user_message|
Servers\AI.MySQL\aisu|register\Sort<|||>1<|||>1_name|
Servers\AI.MySQL\aisu|registerfacilty\Sort<|||>1<|||>1_name|
Servers\AI.MySQL\aisu|responses\Sort<|||>1<|||>0_user_message|
Servers\AI.MySQL\aisu|statistics\Sort<|||>1<|||>1_total_students|
Servers\AI.MySQL\aisu|student\Sort<|||>1<|||>1_id|
Servers\AI.MySQL\ai|admin\Sort<|||>1<|||>1_username|
Servers\AI.MySQL\QueryHistory\2<|||>1<|||>2024-10-28 11:01:58|aisu|0|
Servers\Laragon.MySQL\SessionCreated<|||>1<|||>2022-09-09 20:36:07
Servers\Laragon.MySQL\Host<|||>1<|||>127.0.0.1
Servers\Laragon.MySQL\WindowsAuth<|||>3<|||>0
Servers\Laragon.MySQL\CleartextPluginEnabled<|||>3<|||>0
Servers\Laragon.MySQL\User<|||>1<|||>root
Servers\Laragon.MySQL\Password<|||>1<|||>2
Servers\Laragon.MySQL\LoginPrompt<|||>3<|||>0
Servers\Laragon.MySQL\Port<|||>1<|||>3306
Servers\Laragon.MySQL\NetType<|||>3<|||>0
Servers\Laragon.MySQL\Compressed<|||>3<|||>0
Servers\Laragon.MySQL\LocalTimeZone<|||>3<|||>0
Servers\Laragon.MySQL\QueryTimeout<|||>3<|||>30
Servers\Laragon.MySQL\KeepAlive<|||>3<|||>20
Servers\Laragon.MySQL\FullTableStatus<|||>3<|||>1
Servers\Laragon.MySQL\Databases<|||>1<|||>
Servers\Laragon.MySQL\Library<|||>1<|||>libmysql.dll
Servers\Laragon.MySQL\Comment<|||>1<|||>
Servers\Laragon.MySQL\StartupScriptFilename<|||>1<|||>
Servers\Laragon.MySQL\TreeBackground<|||>3<|||>536870911
Servers\Laragon.MySQL\SshExecutable<|||>1<|||>plink.exe
Servers\Laragon.MySQL\SSHtunnelHost<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelHostPort<|||>3<|||>22
Servers\Laragon.MySQL\SSHtunnelUser<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPassword<|||>1<|||>2
Servers\Laragon.MySQL\SSHtunnelTimeout<|||>3<|||>4
Servers\Laragon.MySQL\SSHtunnelPrivateKey<|||>1<|||>
Servers\Laragon.MySQL\SSHtunnelPort<|||>3<|||>3307
Servers\Laragon.MySQL\SSL_Active<|||>3<|||>0
Servers\Laragon.MySQL\SSL_Key<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cert<|||>1<|||>
Servers\Laragon.MySQL\SSL_CA<|||>1<|||>
Servers\Laragon.MySQL\SSL_Cipher<|||>1<|||>
Servers\Laragon.MySQL\IgnoreDatabasePattern<|||>1<|||>
Servers\Laragon.MySQL\LogFileDdl<|||>3<|||>0
Servers\Laragon.MySQL\LogFileDml<|||>3<|||>0
Servers\Laragon.MySQL\LogFilePath<|||>1<|||>C:\Users\Administrator\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\Laragon.MySQL\RefusedCount<|||>3<|||>2
Servers\Laragon.MySQL\ServerVersionFull<|||>1<|||>8.0.30 - MySQL Community Server - GPL
Servers\Laragon.MySQL\ConnectCount<|||>3<|||>6
Servers\Laragon.MySQL\ServerVersion<|||>3<|||>80030
Servers\Laragon.MySQL\LastConnect<|||>1<|||>2024-07-30 11:49:40
Servers\Laragon.MySQL\lastUsedDB<|||>1<|||>ecares
Servers\Laragon.MySQL\ecares|login\Sort<|||>1<|||>0_username|0_password|0_id|
Servers\testing\SessionCreated<|||>1<|||>2025-01-20 11:46:32
Servers\testing\Host<|||>1<|||>127.0.0.1
Servers\testing\WindowsAuth<|||>3<|||>0
Servers\testing\CleartextPluginEnabled<|||>3<|||>0
Servers\testing\User<|||>1<|||>root
Servers\testing\Password<|||>1<|||>9
Servers\testing\LoginPrompt<|||>3<|||>0
Servers\testing\Port<|||>1<|||>3306
Servers\testing\NetType<|||>3<|||>0
Servers\testing\Compressed<|||>3<|||>0
Servers\testing\LocalTimeZone<|||>3<|||>0
Servers\testing\QueryTimeout<|||>3<|||>30
Servers\testing\KeepAlive<|||>3<|||>20
Servers\testing\FullTableStatus<|||>3<|||>1
Servers\testing\Databases<|||>1<|||>
Servers\testing\Library<|||>1<|||>libmariadb.dll
Servers\testing\Comment<|||>1<|||>
Servers\testing\StartupScriptFilename<|||>1<|||>
Servers\testing\TreeBackground<|||>3<|||>536870911
Servers\testing\SshExecutable<|||>1<|||>
Servers\testing\SSHtunnelHost<|||>1<|||>
Servers\testing\SSHtunnelHostPort<|||>3<|||>22
Servers\testing\SSHtunnelUser<|||>1<|||>
Servers\testing\SSHtunnelPassword<|||>1<|||>3
Servers\testing\SSHtunnelTimeout<|||>3<|||>4
Servers\testing\SSHtunnelPrivateKey<|||>1<|||>
Servers\testing\SSHtunnelPort<|||>3<|||>3307
Servers\testing\SSL_Active<|||>3<|||>0
Servers\testing\SSL_Key<|||>1<|||>
Servers\testing\SSL_Cert<|||>1<|||>
Servers\testing\SSL_CA<|||>1<|||>
Servers\testing\SSL_Cipher<|||>1<|||>
Servers\testing\IgnoreDatabasePattern<|||>1<|||>
Servers\testing\LogFileDdl<|||>3<|||>0
Servers\testing\LogFileDml<|||>3<|||>0
Servers\testing\LogFilePath<|||>1<|||>C:\Users\Admin\AppData\Roaming\HeidiSQL\Logs\%session\%db\%y%m%d.sql
Servers\testing\ServerVersionFull<|||>1<|||>8.0.30 - MySQL Community Server - GPL
Servers\testing\ConnectCount<|||>3<|||>1
Servers\testing\ServerVersion<|||>3<|||>80030
Servers\testing\LastConnect<|||>1<|||>2025-01-20 11:46:46
Servers\testing\lastUsedDB<|||>1<|||>testing
Servers\testing\RefusedCount<|||>3<|||>3
Servers\testing\testing|testing\Sort<|||>1<|||>0_name|
